export const TECH_FILTERS = {
  REACT: "React",
  LARAVEL: "Laravel",
  TYPESCRIPT: "TypeScript",
  JAVASCRIPT: "JavaScript",
  JQUERY: "jQuery",
  TAILWINDCSS: "Tailwind CSS",
  BOOTSTRAP: "Bootstrap",
  HTML_CSS: "HTML/CSS",
  PHP: "PHP",
  JAVA: "Java",
  PYTHON: "Python",
  CSHARP: "C#",
  ANDROID_SDK: "Android SDK",
  FIREBASE: "Firebase",
  MYSQL: "MySQL",
};
